source 'https://rubygems.org'

gem 'rails', '~> 7.1'
gem 'puma', '~> 6.0'
gem 'pg', '~> 1.5'

# OpenTelemetry SDK and exporters
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
# OTLP logs export (ship logs to OpenTelemetry endpoint)
gem 'opentelemetry-logs-api'
gem 'opentelemetry-logs-sdk'
gem 'opentelemetry-exporter-otlp-logs'

# Auto-instrumentation
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-instrumentation-rails'
gem 'opentelemetry-instrumentation-rack'

# Logging
gem 'rails_semantic_logger'
