source 'https://rubygems.org'

gem 'rails', '~> 7.1'
gem 'puma', '~> 6.0'

# OpenTelemetry SDK and exporters
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'

# Auto-instrumentation
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-instrumentation-rails'
gem 'opentelemetry-instrumentation-rack'

# Logging
gem 'rails_semantic_logger'
